export const DEFAULT_LIMIT_PAGINATION = 10
export const DEFAULT_PAGE_PAGINATION = 1
export const DEFAULT_TOTAL_PAGINATION = 0

export const DEFAULT_LIMIT_PAGINATION_S = 5

export const DEFAULT_PAGINATION = {
  page: DEFAULT_PAGE_PAGINATION,
  limit: DEFAULT_LIMIT_PAGINATION_S,
  total: DEFAULT_TOTAL_PAGINATION,
}

export const NEW_POST_ID = 'new'
export const MIN_TEXTAREA_HEIGHT = 32
